<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
             xmlns:wsp="http://www.w3.org/ns/ws-policy"
             xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://redpill.default"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             targetNamespace="http://test.default"
             name="redpillService">
<types>
    <xs:schema xmlns:tns="http://redpill.default"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           version="1.0"
           targetNamespace="http://redpill.default">
    </xs:schema>
</types>


<portType name="wodeservice">
</portType>

<binding name="redpillPortBinding" type="tns:wodeservice">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
</binding>

<service name="redpillService">
<port name="redpillPort" binding="tns:redpillPortBinding">
<soap:address location="127.0.0.1:8088/mulewsps"/>
</port>
</service>
</definitions>